// Reading-mode content index: groups openstaxLinks.json sections by chapter
// ("5.6" -> chapter 5). Book sections live in public/textbook/<book>/<section>.html
// (official cnx-transforms output staged by cnxml/scripts/build_html.py).
import linksJson from '@core/config/openstaxLinks.json'

export interface SectionMeta { title: string; moduleId: string; url: string }
export interface Chapter { num: number; sections: { section: string; meta: SectionMeta }[] }

const links = linksJson as Record<string, { sections: Record<string, SectionMeta> }>

export function availableBooks(): { id: string }[] {
  return Object.keys(links).map(id => ({ id }))
}

// Book id -> staged HTML dir under public/textbook/ (official cnx-transforms
// fragments; generated by cnxml/scripts/build_html.py).
const CONTENT_DIRS: Record<string, string> = {
  'calculus-volume-1': 'calc1',
}

export function contentDirFor(bookId: string): string | null {
  return CONTENT_DIRS[bookId] ?? null
}

/** Flat ordered list of section numbers across all chapters. */
export function flatSections(bookId: string): string[] {
  return chapters(bookId).flatMap(c => c.sections.map(s => s.section))
}

export function chapters(bookId: string): Chapter[] {
  const sections = links[bookId]?.sections ?? {}
  const byChapter = new Map<number, Chapter>()
  for (const [section, meta] of Object.entries(sections)) {
    const num = Number(section.split('.')[0])
    if (!byChapter.has(num)) byChapter.set(num, { num, sections: [] })
    byChapter.get(num)!.sections.push({ section, meta })
  }
  return [...byChapter.values()].sort((a, b) => a.num - b.num)
}

export function sectionMeta(bookId: string, section: string): SectionMeta | null {
  return links[bookId]?.sections?.[section] ?? null
}
