/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrandLogoNav: typeof import('./components/BrandLogoNav.vue')['default']
    BuildTimeIndicator: typeof import('./components/BuildTimeIndicator.vue')['default']
    GridInput: typeof import('./components/problem-input/GridInput.vue')['default']
    HintSystem: typeof import('./components/problem-layout/HintSystem.vue')['default']
    MathField: typeof import('./components/MathField.vue')['default']
    MathText: typeof import('./components/MathText.vue')['default']
    MatrixInput: typeof import('./components/problem-input/MatrixInput.vue')['default']
    MultipleChoice: typeof import('./components/problem-input/MultipleChoice.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NProgress: typeof import('naive-ui')['NProgress']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NResult: typeof import('naive-ui')['NResult']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    Problem: typeof import('./components/problem-layout/Problem.vue')['default']
    ProblemCard: typeof import('./components/problem-layout/ProblemCard.vue')['default']
    ProblemInput: typeof import('./components/problem-input/ProblemInput.vue')['default']
    RenderText: typeof import('./components/RenderText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spacer: typeof import('./components/Spacer.vue')['default']
  }
}
